name: Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: 💾 Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: '0'

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '26.4.0'
          registry-url: 'https://registry.npmjs.org'

      - name: 🧰 Install 
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: ✨ Lint 
        uses: borales/actions-yarn@v5
        with:
          cmd: lint

      - name: 🏷️ Tag
        id: tagging
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAJOR_STRING_TOKEN: \[ci major\]
          MINOR_STRING_TOKEN: \[ci minor\]
          PATCH_STRING_TOKEN: \[ci patch\]
          NONE_STRING_TOKEN: \[ci skip\]
          BRANCH_HISTORY: last
          DRY_RUN: true

      - name: 👊 Bump
        run: |
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]

          yarn version --new-version ${{ steps.tagging.outputs.new_tag }} --message "Version bump to v${{ steps.tagging.outputs.new_tag }} [ci skip]"
          git push --follow-tags

      - name: 📦 Publish
        run: npm publish --provenance
